// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | TextCenteredSlice
  | VideoCarouselSlice
  | FeaturedBannerSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *FeaturedBanner → Primary*
 */
export interface FeaturedBannerSliceDefaultPrimary {
  /**
   * Feature Title field in *FeaturedBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_banner.primary.feature_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  feature_title: prismic.KeyTextField;

  /**
   * Main Title field in *FeaturedBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_banner.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title: prismic.KeyTextField;

  /**
   * Description field in *FeaturedBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_banner.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Button Text field in *FeaturedBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_banner.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Image field in *FeaturedBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default Variation variation for FeaturedBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with all fields
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedBanner*
 */
type FeaturedBannerSliceVariation = FeaturedBannerSliceDefault;

/**
 * FeaturedBanner Shared Slice
 *
 * - **API ID**: `featured_banner`
 * - **Description**: A banner featuring a talk with a title, description, and image.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedBannerSlice = prismic.SharedSlice<
  "featured_banner",
  FeaturedBannerSliceVariation
>;

/**
 * Primary content in *TextCentered → Primary*
 */
export interface TextCenteredSliceDefaultPrimary {
  /**
   * Title field in *TextCentered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_centered.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *TextCentered → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_centered.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default Variation variation for TextCentered Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with all fields
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCenteredSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextCenteredSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextCentered*
 */
type TextCenteredSliceVariation = TextCenteredSliceDefault;

/**
 * TextCentered Shared Slice
 *
 * - **API ID**: `text_centered`
 * - **Description**: Centered text block with a title and a paragraph.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCenteredSlice = prismic.SharedSlice<
  "text_centered",
  TextCenteredSliceVariation
>;

/**
 * Primary content in *VideoCarousel → Items*
 */
export interface VideoCarouselSliceDefaultItem {
  /**
   * Video Image field in *VideoCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.items[].video_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_image: prismic.ImageField<never>;

  /**
   * Video Title field in *VideoCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.items[].video_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_title: prismic.KeyTextField;

  /**
   * Author field in *VideoCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.items[].video_author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_author: prismic.KeyTextField;
}

/**
 * Default Variation variation for VideoCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard video carousel layout.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<VideoCarouselSliceDefaultItem>
>;

/**
 * Primary content in *VideoCarousel → Items*
 */
export interface VideoCarouselSliceSmallItem {
  /**
   * Video Image field in *VideoCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.items[].video_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  video_image: prismic.ImageField<never>;

  /**
   * Video Title field in *VideoCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.items[].video_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_title: prismic.KeyTextField;

  /**
   * Author field in *VideoCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.items[].video_author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_author: prismic.KeyTextField;

  /**
   * Month field in *VideoCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.items[].video_month
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_month: prismic.KeyTextField;
}

/**
 * Small Variation variation for VideoCarousel Slice
 *
 * - **API ID**: `small`
 * - **Description**: Smaller video carousel layout.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoCarouselSliceSmall = prismic.SharedSliceVariation<
  "small",
  Record<string, never>,
  Simplify<VideoCarouselSliceSmallItem>
>;

/**
 * Slice variation for *VideoCarousel*
 */
type VideoCarouselSliceVariation =
  | VideoCarouselSliceDefault
  | VideoCarouselSliceSmall;

/**
 * VideoCarousel Shared Slice
 *
 * - **API ID**: `video_carousel`
 * - **Description**: Carousel for displaying videos with two variations for layout sizes.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoCarouselSlice = prismic.SharedSlice<
  "video_carousel",
  VideoCarouselSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      FeaturedBannerSlice,
      FeaturedBannerSliceDefaultPrimary,
      FeaturedBannerSliceVariation,
      FeaturedBannerSliceDefault,
      TextCenteredSlice,
      TextCenteredSliceDefaultPrimary,
      TextCenteredSliceVariation,
      TextCenteredSliceDefault,
      VideoCarouselSlice,
      VideoCarouselSliceDefaultItem,
      VideoCarouselSliceSmallItem,
      VideoCarouselSliceVariation,
      VideoCarouselSliceDefault,
      VideoCarouselSliceSmall,
    };
  }
}
