// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_banner: dynamic(() => import("./FeaturedBanner")),
  text_centered: dynamic(() => import("./TextCentered")),
  video_carousel: dynamic(() => import("./VideoCarousel")),
};
